//export const SCHEME = 'SCHEME';
//ERROR TYPES
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//AUTH TYPES
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//UPLOAD TYPES
export const ADD_IMAGES = 'ADD_IMAGES';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';
export const DELETE_IMAGE = 'DELETE_IMAGE';

//CONTAINER TYPES
export const SET_UPCOMING_CONTAINERS = 'SET_UPCOMING_CONTAINERS';
export const SET_PAST_CONTAINERS = 'SET_PAST_CONTAINERS';
export const SET_INPROGRESS_CONTAINERS = 'SET_INPROGRESS_CONTAINERS';
export const GET_CONTAINER = 'GET_CONTAINER';
export const CREATE_CONTAINER = 'CREATE_CONTAINER';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const CLEAR_CONTAINER = 'CLEAR_CONTAINER';
export const CLEAR_CONTAINERS = 'CLEAR_CONTAINERS';

/**
    SET_UPCOMING_CONTAINERS,
    SET_PAST_CONTAINERS,
    SET_INPROGRESS_CONTAINERS, */

//Google maps
export const SET_DIRECTION_SERVICE = 'SET_DIRECTION_SERVICE';
export const SET_DIRECTION_RENDERER = 'SET_DIRECTION_RENDERER';
export const SET_ENDPOINT = 'SET_ENDPOINT';
export const SET_STARTPOINT = 'SET_STARTPOINT';
export const SET_WAYPOINTS = 'SET_WAYPOINTS';
export const SET_MAP = 'SET_MAP';
export const SET_DIRECTION_RESULTS = 'SET_DIRECTION_RESULTS';
export const DEL_WAYPOINTS = 'DEL_WAYPOINTS';
export const CLEAR_MAPS = 'CLEAR_MAPS';